language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - ant

before_script:
  - nvm install 6
  - echo `which node`
env:
  - ANDROID_PLATFORM="platforms;android-25" ANDROID_SYSTEM_IMAGE="system-images;android-25;google_apis;armeabi-v7a" TAG="google_apis" ABI="armeabi-v7a"

script: bash .travis/build-android.sh
