branches:
    only:
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - ant

before_script:
  - nvm install 6
  - echo `which node`

script:
 #- cat `which android-wait-for-emulator`
 - wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
 - unzip -q platform-tools-latest-linux.zip -d ../
 - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
 - unzip -q sdk-tools-linux-3859397.zip -d ../
 - echo yes | ../tools/bin/sdkmanager "tools"
 - echo yes | ../tools/bin/sdkmanager "platforms;android-25"
 - echo yes | ../tools/bin/sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
 - echo yes | ../tools/bin/sdkmanager "emulator"
 - echo no | ../tools/bin/avdmanager create avd -k "system-images;android-25;google_apis;armeabi-v7a" -n test -f --tag google_apis --abi armeabi-v7a
 - ../tools/emulator -avd test -no-audio -no-window &
 - cd ..
 - export PATH=`pwd`/tools:`pwd`/platform-tools:`pwd`/tools/bin:$PATH
 - cd cn1-unit-tests-android
 - wget https://github.com/codenameone/cn1-binaries/archive/master.zip
 - unzip -q master.zip -d ../
 - mv ../cn1-binaries-master ../cn1-binaries
 - rm master.zip
 - wget https://github.com/codenameone/codenameone-skins/archive/master.zip
 - unzip -q master.zip -d ../
 - mv ../codenameone-skins-master ../codenameone-skins
 - cd ../codenameone-skins
 - ./build_skins.sh
 - wget https://github.com/codenameone/CodenameOne/archive/master.zip
 - unzip -q master.zip -d ../
 - mv ../CodenameOne-master ../cn1
 - cd ../cn1
 - cd CodenameOne
 - ant jar
 - cd ../CodenameOneDesigner
 - mkdir dist
 - mkdir dist/lib
 - ant release
 - mkdir ../../codenameone-cli
 - cd ../../codenameone-cli
 - npm install codenameone-cli
 - wget https://github.com/shannah/cn1-unit-tests/archive/master.zip
 - unzip -q master.zip -d ../
 - mv ../cn1-unit-tests-master ../cn1-unit-tests
 - rm master.zip
 - cd ../cn1-unit-tests
 - bash ../cn1-unit-tests-android/android-waiting-for-emulator.sh
 - adb shell settings put global window_animation_scale 0 &
 - adb shell settings put global transition_animation_scale 0 &
 - adb shell settings put global animator_duration_scale 0 &
 - sleep 30
 - adb shell input keyevent 82 &
 - ../codenameone-cli/node_modules/.bin/cn1 test -cn1Sources ../cn1 -s -e -t android -skipCompileCn1Sources -v
