branches:
    only:
        - 18
        - 19
        - 21
        - 22
language: android
jdk: oraclejdk8
addons:
  apt:
    packages:
      - ant
android:
  components:
    - platform-tools
    - android-18
    - sys-img-armeabi-v7a-android-18

before_script:
  - nvm install 6
  - echo `which node`
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-18 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter sysimg-18 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
 - wget https://github.com/codenameone/cn1-binaries/archive/master.zip
 - unzip master.zip -d ../
 - mv ../cn1-binaries-master ../cn1-binaries
 - rm master.zip
 - wget https://github.com/codenameone/codenameone-skins/archive/master.zip
 - unzip master.zip -d ../
 - mv ../codenameone-skins-master ../codenameone-skins
 - cd ../codenameone-skins
 - ./build_skins.sh
 - wget https://github.com/codenameone/CodenameOne/archive/master.zip
 - unzip master.zip -d ../
 - mv ../CodenameOne-master ../cn1
 - cd ../cn1
 - cd CodenameOne
 - ant jar
 - cd ../CodenameOneDesigner
 - mkdir dist
 - mkdir dist/lib
 - ant release
 - mkdir ../../codenameone-cli
 - cd ../../codenameone-cli
 - npm install codenameone-cli
 - wget https://github.com/shannah/cn1-unit-tests/archive/master.zip
 - unzip master.zip -d ../
 - mv ../cn1-unit-tests-master ../cn1-unit-tests
 - rm master.zip
 - cd ../cn1-unit-tests
 - sh ../cn1-unit-tests-android/wait-for-emulator.sh
 - adb shell input keyevent 82 &
 - ../codenameone-cli/node_modules/.bin/cn1 test -cn1Sources ../cn1 -s -e -t android -skipCompileCn1Sources -v
